linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/config/routes.rb
Rails.application.routes.draw do
  resources :carros
  # home é o controller e index é a ação lá do controller.
  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/models/carro.rb
class Carro < ApplicationRecord
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/models/usuario.rb
class Usuario < ApplicationRecord
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy

    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:nome, :marca, :valor, :quantidade)
    end
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/helpers/carros_helper.rb
module CarrosHelper
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/helpers/home_helper.rb
module HomeHelper
end

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/_carro.html.erb
<div id="<%= dom_id carro %>" >
  <p class="atributo">
    <strong>Nome:</strong>
    <%= carro.nome %>
  </p>

  <p class="atributo">
    <strong>Marca:</strong>
    <%= carro.marca %>
  </p>

  <p class="atributo">
    <strong>Valor:</strong>
    <%= carro.valor %>
  </p>

  <p class="atributo">
    <strong>Quantidade:</strong>
    <%= carro.quantidade %>
  </p>

  <p class="atributo">
    <strong>Ativo:</strong>
    <%= carro.ativo %>
  </p>

</div>

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/_form.html.erb
<%= form_with(model: carro) do |form| %>
  <% if carro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
        <% carro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :marca, style: "display: block" %>
    <%= form.text_field :marca %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Show this carro", @carro %> |
  <%= link_to "Back to carros", carros_path %>
</div>

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carros</h1>

<div id="carros" class="show_carros">
  <% @carros.each do |carro| %>
    <%= render carro %>
    <p>
      <%= link_to "Show this carro", carro %>
    </p>
  <% end %>
</div>

<%= link_to "New carro", new_carro_path %>

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Back to carros", carros_path %>
</div>

linguagem_ruby/lib/linguagem_ruby/aula26_rails_generators/app_rails_mysql/app/views/carros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @carro %>

<div>
  <%= link_to "Edit this carro", edit_carro_path(@carro) %> |
  <%= link_to "Back to carros", carros_path %>

  <%= button_to "Destroy this carro", @carro, method: :delete %>
</div>